---
title: "ANCOVA Practice"
output: html_document
editor_options: 
  markdown: 
    wrap: 72
---
```{r setup2, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, echo = TRUE, include=TRUE)
####TOGGLE the 'include' OPTION FOR STUDENT vs. KEY VERSION of EXAM####
```

##  {.tabset}

### Load Libraries

```{r setup, warning = FALSE, message = FALSE, include=TRUE}
library(readr)
library(tidyr)
library(dplyr)
library(ggplot2)
library(emmeans)
library(multcomp)
```

------------------------------------------------------------------------

### Question 1

```{r data 1}
d1 <- msleep %>%
  filter(order == "Carnivora" | order == "Rodentia") %>%
  filter(!is.na(sleep_total)) %>%
  filter(!is.na(sleep_rem))
```

```{r plot 1}
p1 <- 
  ggplot(d1, aes(sleep_total, sleep_rem, color=order))+
  geom_point(size=5) +
  geom_smooth(method = 'lm', se=FALSE) + ##sep. slopes is the default
  theme_bw()
p1
```


```{r model 1}
m1 <- lm(sleep_rem~sleep_total*order, data=d1)
anova(m1)
```
```{r summary m1}
summary(m1)
```

No significant interaction, so no evidence that lines should be allowed to cross. Remove the 
interaction term -> refit mode -> replot the figure

```{r}
m2 <- lm(sleep_rem~sleep_total+ order, data=d1)
anova(m2)
```
```{r predictions for same slopes model}
predictions_m2 <- predict(m2) #forces lines to be parallel
```

```{r plot 2}
p2 <- 
  ggplot(d1, aes(sleep_total, sleep_rem, color=order))+
  geom_point(size=5) +
  geom_line(aes(y = predictions_m2)) +
  theme_bw()
p2
```

Results statement here...