---
title: "Chapter 6 Analysis of Covariance (ANCOVA)"
author: "C.M. Gienger"
date: "November 27, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(HH)
library(dplyr)
library(ggplot2)
library(ggfortify)
```

```{r cars}
#import and view data
limp <- read.csv("limpet.csv")
View(limp)
glimpse(limp)

#as always, we make a plot to visualize data
ggplot(limp, aes(x = DENSITY, y = EGGS, colour = SEASON)) +
  geom_point() +
  scale_color_manual(values = c(spring="green", summer="red")) +
  theme_bw()

# Can also use the 'ancovaplot' function in the HH package to plot and fit lines
ancovaplot(EGGS ~ DENSITY + SEASON, data=limp) #equal slopes plot
ancovaplot(EGGS ~ DENSITY * SEASON, data=limp) #separate slopes plot

#specify the ANCOVA model
limp.mod <- lm(EGGS ~ DENSITY * SEASON, data = limp)

#details about the model
names(limp.mod)

#check model assumptions
autoplot(limp.mod, smooth.colour = NA)

#interpret the model
anova(limp.mod)
summary(limp.mod)

#fit model WITHOUT interaction (since we remove N.S. interaction terms)
limp.mod.nointeraction <- lm(EGGS ~ DENSITY + SEASON, data = limp)
anova(limp.mod.nointeraction)
summary(limp.mod.nointeraction)

#doesn't change much because slope and seasons were already significant
#we are just re-assigning the '0.0118' variation from interaction back
#to the other model terms.

#compare the two models
anova(limp.mod, limp.mod.nointeraction)
#they have statistically similar explanatory power

```
